import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
   <div className={"page-template-template-homepage-v3"}>
      <Head>
        <title>G Projukti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
    </div>
  )
}
